// This file is @generated by prost-build.
/// / A single message in a produce request.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Record {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// / A single message returned in a fetch response.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchedRecord {
    #[prost(int64, tag = "1")]
    pub offset: i64,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "3")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicMetadataRequest {
    #[prost(string, repeated, tag = "1")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicMetadataResponse {
    #[prost(message, repeated, tag = "1")]
    pub brokers: ::prost::alloc::vec::Vec<topic_metadata_response::Broker>,
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<topic_metadata_response::TopicMetadata>,
}
/// Nested message and enum types in `TopicMetadataResponse`.
pub mod topic_metadata_response {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Broker {
        #[prost(int32, tag = "1")]
        pub node_id: i32,
        #[prost(string, tag = "2")]
        pub host: ::prost::alloc::string::String,
        #[prost(int32, tag = "3")]
        pub port: i32,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicMetadata {
        #[prost(int32, tag = "1")]
        pub topic_error_code: i32,
        #[prost(string, tag = "2")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "3")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionMetadata>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PartitionMetadata {
        #[prost(int32, tag = "1")]
        pub partition_error_code: i32,
        #[prost(int32, tag = "2")]
        pub partition_id: i32,
        #[prost(int32, tag = "3")]
        pub leader: i32,
        #[prost(int32, repeated, tag = "4")]
        pub replicas: ::prost::alloc::vec::Vec<i32>,
        /// In-Sync Replicas
        #[prost(int32, repeated, tag = "5")]
        pub isr: ::prost::alloc::vec::Vec<i32>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProduceRequest {
    /// -1=all, 0=none, 1=leader
    #[prost(int32, tag = "1")]
    pub required_acks: i32,
    #[prost(int32, tag = "2")]
    pub timeout_ms: i32,
    #[prost(message, repeated, tag = "3")]
    pub topics: ::prost::alloc::vec::Vec<produce_request::TopicData>,
}
/// Nested message and enum types in `ProduceRequest`.
pub mod produce_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicData {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionData>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PartitionData {
        #[prost(int32, tag = "1")]
        pub partition: i32,
        #[prost(message, repeated, tag = "2")]
        pub records: ::prost::alloc::vec::Vec<super::Record>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProduceResponse {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<produce_response::TopicResult>,
}
/// Nested message and enum types in `ProduceResponse`.
pub mod produce_response {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicResult {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionResult>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PartitionResult {
        #[prost(int32, tag = "1")]
        pub partition: i32,
        #[prost(int32, tag = "2")]
        pub error_code: i32,
        #[prost(int64, tag = "3")]
        pub offset: i64,
        /// set when error_code = NOT_LEADER_FOR_PARTITION
        #[prost(string, tag = "4")]
        pub leader_addr: ::prost::alloc::string::String,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchRequest {
    /// -1 for consumer
    #[prost(int32, tag = "1")]
    pub replica_id: i32,
    /// Max time to wait (ms)
    #[prost(int32, tag = "2")]
    pub max_wait_time: i32,
    /// Min bytes to respond
    #[prost(int32, tag = "3")]
    pub min_bytes: i32,
    #[prost(message, repeated, tag = "4")]
    pub topics: ::prost::alloc::vec::Vec<fetch_request::TopicData>,
}
/// Nested message and enum types in `FetchRequest`.
pub mod fetch_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicData {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionData>,
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct PartitionData {
        #[prost(int32, tag = "1")]
        pub partition: i32,
        #[prost(int64, tag = "2")]
        pub fetch_offset: i64,
        #[prost(int32, tag = "3")]
        pub max_bytes: i32,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchResponse {
    #[prost(message, repeated, tag = "1")]
    pub topics: ::prost::alloc::vec::Vec<fetch_response::TopicResult>,
}
/// Nested message and enum types in `FetchResponse`.
pub mod fetch_response {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicResult {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionResult>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PartitionResult {
        #[prost(int32, tag = "1")]
        pub partition: i32,
        #[prost(int32, tag = "2")]
        pub error_code: i32,
        #[prost(int64, tag = "3")]
        pub high_watermark_offset: i64,
        #[prost(message, repeated, tag = "4")]
        pub records: ::prost::alloc::vec::Vec<super::FetchedRecord>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOffsetsRequest {
    #[prost(int32, tag = "1")]
    pub replica_id: i32,
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<list_offsets_request::TopicData>,
}
/// Nested message and enum types in `ListOffsetsRequest`.
pub mod list_offsets_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicData {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionData>,
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct PartitionData {
        #[prost(int32, tag = "1")]
        pub partition: i32,
        /// -1=latest, -2=earliest
        #[prost(int64, tag = "2")]
        pub time: i64,
        #[prost(int32, tag = "3")]
        pub max_number_of_offsets: i32,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOffsetsResponse {
    #[prost(message, repeated, tag = "1")]
    pub topics: ::prost::alloc::vec::Vec<list_offsets_response::TopicResult>,
}
/// Nested message and enum types in `ListOffsetsResponse`.
pub mod list_offsets_response {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicResult {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionOffsets>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PartitionOffsets {
        #[prost(int32, tag = "1")]
        pub partition: i32,
        #[prost(int32, tag = "2")]
        pub error_code: i32,
        #[prost(int64, repeated, tag = "3")]
        pub offsets: ::prost::alloc::vec::Vec<i64>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupCoordinatorRequest {
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupCoordinatorResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(int32, tag = "2")]
    pub coordinator_id: i32,
    #[prost(string, tag = "3")]
    pub coordinator_host: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub coordinator_port: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinGroupRequest {
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub session_timeout: i32,
    #[prost(string, tag = "3")]
    pub member_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub protocol_type: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub group_protocols: ::prost::alloc::vec::Vec<join_group_request::GroupProtocol>,
}
/// Nested message and enum types in `JoinGroupRequest`.
pub mod join_group_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct GroupProtocol {
        #[prost(string, tag = "1")]
        pub protocol_name: ::prost::alloc::string::String,
        #[prost(bytes = "vec", tag = "2")]
        pub protocol_metadata: ::prost::alloc::vec::Vec<u8>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinGroupResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(int32, tag = "2")]
    pub generation_id: i32,
    #[prost(string, tag = "3")]
    pub group_protocol: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub leader_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub member_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub members: ::prost::alloc::vec::Vec<join_group_response::Member>,
}
/// Nested message and enum types in `JoinGroupResponse`.
pub mod join_group_response {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Member {
        #[prost(string, tag = "1")]
        pub member_id: ::prost::alloc::string::String,
        #[prost(bytes = "vec", tag = "2")]
        pub member_metadata: ::prost::alloc::vec::Vec<u8>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncGroupRequest {
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub generation_id: i32,
    #[prost(string, tag = "3")]
    pub member_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub group_assignment: ::prost::alloc::vec::Vec<sync_group_request::Assignment>,
}
/// Nested message and enum types in `SyncGroupRequest`.
pub mod sync_group_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Assignment {
        #[prost(string, tag = "1")]
        pub member_id: ::prost::alloc::string::String,
        #[prost(bytes = "vec", tag = "2")]
        pub member_assignment: ::prost::alloc::vec::Vec<u8>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncGroupResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub member_assignment: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatRequest {
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub generation_id: i32,
    #[prost(string, tag = "3")]
    pub member_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HeartbeatResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaveGroupRequest {
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub member_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaveGroupResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OffsetCommitRequest {
    #[prost(string, tag = "1")]
    pub consumer_group_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<offset_commit_request::TopicData>,
}
/// Nested message and enum types in `OffsetCommitRequest`.
pub mod offset_commit_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicData {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionData>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PartitionData {
        #[prost(int32, tag = "1")]
        pub partition: i32,
        #[prost(int64, tag = "2")]
        pub offset: i64,
        #[prost(string, tag = "3")]
        pub metadata: ::prost::alloc::string::String,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OffsetCommitResponse {
    #[prost(message, repeated, tag = "1")]
    pub topics: ::prost::alloc::vec::Vec<offset_commit_response::TopicResult>,
}
/// Nested message and enum types in `OffsetCommitResponse`.
pub mod offset_commit_response {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicResult {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionResult>,
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct PartitionResult {
        #[prost(int32, tag = "1")]
        pub partition: i32,
        #[prost(int32, tag = "2")]
        pub error_code: i32,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OffsetFetchRequest {
    #[prost(string, tag = "1")]
    pub consumer_group_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<offset_fetch_request::TopicData>,
}
/// Nested message and enum types in `OffsetFetchRequest`.
pub mod offset_fetch_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicData {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(int32, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<i32>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OffsetFetchResponse {
    #[prost(message, repeated, tag = "1")]
    pub topics: ::prost::alloc::vec::Vec<offset_fetch_response::TopicResult>,
}
/// Nested message and enum types in `OffsetFetchResponse`.
pub mod offset_fetch_response {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TopicResult {
        #[prost(string, tag = "1")]
        pub topic_name: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub partitions: ::prost::alloc::vec::Vec<PartitionResult>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PartitionResult {
        #[prost(int32, tag = "1")]
        pub partition: i32,
        #[prost(int64, tag = "2")]
        pub offset: i64,
        #[prost(string, tag = "3")]
        pub metadata: ::prost::alloc::string::String,
        #[prost(int32, tag = "4")]
        pub error_code: i32,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTopicRequest {
    #[prost(string, tag = "1")]
    pub topic_name: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub num_partitions: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTopicResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddNodeRequest {
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    #[prost(string, tag = "2")]
    pub api_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub rpc_addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddNodeResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub leader_addr: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveNodeRequest {
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveNodeResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub leader_addr: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    NoError = 0,
    Unknown = 1,
    OffsetOutOfRange = 2,
    InvalidMessage = 3,
    UnknownTopicOrPartition = 4,
    LeaderNotAvailable = 5,
    NotLeaderForPartition = 6,
    OffsetMetadataTooLarge = 7,
    GroupLoadInProgress = 8,
    GroupCoordinatorNotAvailable = 9,
    NotCoordinatorForGroup = 10,
    InvalidGroupId = 11,
    UnknownMemberId = 12,
    InvalidSessionTimeout = 13,
    RebalanceInProgress = 14,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NoError => "NO_ERROR",
            Self::Unknown => "UNKNOWN",
            Self::OffsetOutOfRange => "OFFSET_OUT_OF_RANGE",
            Self::InvalidMessage => "INVALID_MESSAGE",
            Self::UnknownTopicOrPartition => "UNKNOWN_TOPIC_OR_PARTITION",
            Self::LeaderNotAvailable => "LEADER_NOT_AVAILABLE",
            Self::NotLeaderForPartition => "NOT_LEADER_FOR_PARTITION",
            Self::OffsetMetadataTooLarge => "OFFSET_METADATA_TOO_LARGE",
            Self::GroupLoadInProgress => "GROUP_LOAD_IN_PROGRESS",
            Self::GroupCoordinatorNotAvailable => "GROUP_COORDINATOR_NOT_AVAILABLE",
            Self::NotCoordinatorForGroup => "NOT_COORDINATOR_FOR_GROUP",
            Self::InvalidGroupId => "INVALID_GROUP_ID",
            Self::UnknownMemberId => "UNKNOWN_MEMBER_ID",
            Self::InvalidSessionTimeout => "INVALID_SESSION_TIMEOUT",
            Self::RebalanceInProgress => "REBALANCE_IN_PROGRESS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NO_ERROR" => Some(Self::NoError),
            "UNKNOWN" => Some(Self::Unknown),
            "OFFSET_OUT_OF_RANGE" => Some(Self::OffsetOutOfRange),
            "INVALID_MESSAGE" => Some(Self::InvalidMessage),
            "UNKNOWN_TOPIC_OR_PARTITION" => Some(Self::UnknownTopicOrPartition),
            "LEADER_NOT_AVAILABLE" => Some(Self::LeaderNotAvailable),
            "NOT_LEADER_FOR_PARTITION" => Some(Self::NotLeaderForPartition),
            "OFFSET_METADATA_TOO_LARGE" => Some(Self::OffsetMetadataTooLarge),
            "GROUP_LOAD_IN_PROGRESS" => Some(Self::GroupLoadInProgress),
            "GROUP_COORDINATOR_NOT_AVAILABLE" => Some(Self::GroupCoordinatorNotAvailable),
            "NOT_COORDINATOR_FOR_GROUP" => Some(Self::NotCoordinatorForGroup),
            "INVALID_GROUP_ID" => Some(Self::InvalidGroupId),
            "UNKNOWN_MEMBER_ID" => Some(Self::UnknownMemberId),
            "INVALID_SESSION_TIMEOUT" => Some(Self::InvalidSessionTimeout),
            "REBALANCE_IN_PROGRESS" => Some(Self::RebalanceInProgress),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod broker_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Kafka Broker Service
    #[derive(Debug, Clone)]
    pub struct BrokerClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BrokerClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BrokerClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BrokerClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BrokerClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Topic Management
        pub async fn get_topic_metadata(
            &mut self,
            request: impl tonic::IntoRequest<super::TopicMetadataRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TopicMetadataResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/broker.Broker/GetTopicMetadata",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("broker.Broker", "GetTopicMetadata"));
            self.inner.unary(req, path, codec).await
        }
        /// Producer Operations
        pub async fn produce(
            &mut self,
            request: impl tonic::IntoRequest<super::ProduceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProduceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/broker.Broker/Produce");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "Produce"));
            self.inner.unary(req, path, codec).await
        }
        /// Consumer Operations
        pub async fn fetch(
            &mut self,
            request: impl tonic::IntoRequest<super::FetchRequest>,
        ) -> std::result::Result<tonic::Response<super::FetchResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/broker.Broker/Fetch");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "Fetch"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_offsets(
            &mut self,
            request: impl tonic::IntoRequest<super::ListOffsetsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListOffsetsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/broker.Broker/ListOffsets",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "ListOffsets"));
            self.inner.unary(req, path, codec).await
        }
        /// Consumer Group Coordination
        pub async fn find_coordinator(
            &mut self,
            request: impl tonic::IntoRequest<super::GroupCoordinatorRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GroupCoordinatorResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/broker.Broker/FindCoordinator",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("broker.Broker", "FindCoordinator"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn join_group(
            &mut self,
            request: impl tonic::IntoRequest<super::JoinGroupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::JoinGroupResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/broker.Broker/JoinGroup");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "JoinGroup"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn sync_group(
            &mut self,
            request: impl tonic::IntoRequest<super::SyncGroupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SyncGroupResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/broker.Broker/SyncGroup");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "SyncGroup"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn heartbeat(
            &mut self,
            request: impl tonic::IntoRequest<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/broker.Broker/Heartbeat");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "Heartbeat"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn leave_group(
            &mut self,
            request: impl tonic::IntoRequest<super::LeaveGroupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LeaveGroupResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/broker.Broker/LeaveGroup");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "LeaveGroup"));
            self.inner.unary(req, path, codec).await
        }
        /// Offset Management
        pub async fn commit_offset(
            &mut self,
            request: impl tonic::IntoRequest<super::OffsetCommitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OffsetCommitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/broker.Broker/CommitOffset",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("broker.Broker", "CommitOffset"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn fetch_offset(
            &mut self,
            request: impl tonic::IntoRequest<super::OffsetFetchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OffsetFetchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/broker.Broker/FetchOffset",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "FetchOffset"));
            self.inner.unary(req, path, codec).await
        }
        /// Topic Management
        pub async fn create_topic(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateTopicRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateTopicResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/broker.Broker/CreateTopic",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "CreateTopic"));
            self.inner.unary(req, path, codec).await
        }
        /// Cluster Membership (cluster mode only)
        pub async fn add_node(
            &mut self,
            request: impl tonic::IntoRequest<super::AddNodeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddNodeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/broker.Broker/AddNode");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "AddNode"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn remove_node(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveNodeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveNodeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/broker.Broker/RemoveNode");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("broker.Broker", "RemoveNode"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod broker_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BrokerServer.
    #[async_trait]
    pub trait Broker: std::marker::Send + std::marker::Sync + 'static {
        /// Topic Management
        async fn get_topic_metadata(
            &self,
            request: tonic::Request<super::TopicMetadataRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TopicMetadataResponse>,
            tonic::Status,
        >;
        /// Producer Operations
        async fn produce(
            &self,
            request: tonic::Request<super::ProduceRequest>,
        ) -> std::result::Result<tonic::Response<super::ProduceResponse>, tonic::Status>;
        /// Consumer Operations
        async fn fetch(
            &self,
            request: tonic::Request<super::FetchRequest>,
        ) -> std::result::Result<tonic::Response<super::FetchResponse>, tonic::Status>;
        async fn list_offsets(
            &self,
            request: tonic::Request<super::ListOffsetsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListOffsetsResponse>,
            tonic::Status,
        >;
        /// Consumer Group Coordination
        async fn find_coordinator(
            &self,
            request: tonic::Request<super::GroupCoordinatorRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GroupCoordinatorResponse>,
            tonic::Status,
        >;
        async fn join_group(
            &self,
            request: tonic::Request<super::JoinGroupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::JoinGroupResponse>,
            tonic::Status,
        >;
        async fn sync_group(
            &self,
            request: tonic::Request<super::SyncGroupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SyncGroupResponse>,
            tonic::Status,
        >;
        async fn heartbeat(
            &self,
            request: tonic::Request<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        >;
        async fn leave_group(
            &self,
            request: tonic::Request<super::LeaveGroupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LeaveGroupResponse>,
            tonic::Status,
        >;
        /// Offset Management
        async fn commit_offset(
            &self,
            request: tonic::Request<super::OffsetCommitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OffsetCommitResponse>,
            tonic::Status,
        >;
        async fn fetch_offset(
            &self,
            request: tonic::Request<super::OffsetFetchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OffsetFetchResponse>,
            tonic::Status,
        >;
        /// Topic Management
        async fn create_topic(
            &self,
            request: tonic::Request<super::CreateTopicRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateTopicResponse>,
            tonic::Status,
        >;
        /// Cluster Membership (cluster mode only)
        async fn add_node(
            &self,
            request: tonic::Request<super::AddNodeRequest>,
        ) -> std::result::Result<tonic::Response<super::AddNodeResponse>, tonic::Status>;
        async fn remove_node(
            &self,
            request: tonic::Request<super::RemoveNodeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveNodeResponse>,
            tonic::Status,
        >;
    }
    /// Kafka Broker Service
    #[derive(Debug)]
    pub struct BrokerServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BrokerServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BrokerServer<T>
    where
        T: Broker,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/broker.Broker/GetTopicMetadata" => {
                    #[allow(non_camel_case_types)]
                    struct GetTopicMetadataSvc<T: Broker>(pub Arc<T>);
                    impl<
                        T: Broker,
                    > tonic::server::UnaryService<super::TopicMetadataRequest>
                    for GetTopicMetadataSvc<T> {
                        type Response = super::TopicMetadataResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TopicMetadataRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::get_topic_metadata(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTopicMetadataSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/Produce" => {
                    #[allow(non_camel_case_types)]
                    struct ProduceSvc<T: Broker>(pub Arc<T>);
                    impl<T: Broker> tonic::server::UnaryService<super::ProduceRequest>
                    for ProduceSvc<T> {
                        type Response = super::ProduceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProduceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::produce(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ProduceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/Fetch" => {
                    #[allow(non_camel_case_types)]
                    struct FetchSvc<T: Broker>(pub Arc<T>);
                    impl<T: Broker> tonic::server::UnaryService<super::FetchRequest>
                    for FetchSvc<T> {
                        type Response = super::FetchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FetchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::fetch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FetchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/ListOffsets" => {
                    #[allow(non_camel_case_types)]
                    struct ListOffsetsSvc<T: Broker>(pub Arc<T>);
                    impl<
                        T: Broker,
                    > tonic::server::UnaryService<super::ListOffsetsRequest>
                    for ListOffsetsSvc<T> {
                        type Response = super::ListOffsetsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListOffsetsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::list_offsets(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListOffsetsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/FindCoordinator" => {
                    #[allow(non_camel_case_types)]
                    struct FindCoordinatorSvc<T: Broker>(pub Arc<T>);
                    impl<
                        T: Broker,
                    > tonic::server::UnaryService<super::GroupCoordinatorRequest>
                    for FindCoordinatorSvc<T> {
                        type Response = super::GroupCoordinatorResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GroupCoordinatorRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::find_coordinator(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FindCoordinatorSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/JoinGroup" => {
                    #[allow(non_camel_case_types)]
                    struct JoinGroupSvc<T: Broker>(pub Arc<T>);
                    impl<T: Broker> tonic::server::UnaryService<super::JoinGroupRequest>
                    for JoinGroupSvc<T> {
                        type Response = super::JoinGroupResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::JoinGroupRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::join_group(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = JoinGroupSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/SyncGroup" => {
                    #[allow(non_camel_case_types)]
                    struct SyncGroupSvc<T: Broker>(pub Arc<T>);
                    impl<T: Broker> tonic::server::UnaryService<super::SyncGroupRequest>
                    for SyncGroupSvc<T> {
                        type Response = super::SyncGroupResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SyncGroupRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::sync_group(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SyncGroupSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/Heartbeat" => {
                    #[allow(non_camel_case_types)]
                    struct HeartbeatSvc<T: Broker>(pub Arc<T>);
                    impl<T: Broker> tonic::server::UnaryService<super::HeartbeatRequest>
                    for HeartbeatSvc<T> {
                        type Response = super::HeartbeatResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HeartbeatRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::heartbeat(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HeartbeatSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/LeaveGroup" => {
                    #[allow(non_camel_case_types)]
                    struct LeaveGroupSvc<T: Broker>(pub Arc<T>);
                    impl<T: Broker> tonic::server::UnaryService<super::LeaveGroupRequest>
                    for LeaveGroupSvc<T> {
                        type Response = super::LeaveGroupResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LeaveGroupRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::leave_group(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LeaveGroupSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/CommitOffset" => {
                    #[allow(non_camel_case_types)]
                    struct CommitOffsetSvc<T: Broker>(pub Arc<T>);
                    impl<
                        T: Broker,
                    > tonic::server::UnaryService<super::OffsetCommitRequest>
                    for CommitOffsetSvc<T> {
                        type Response = super::OffsetCommitResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OffsetCommitRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::commit_offset(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CommitOffsetSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/FetchOffset" => {
                    #[allow(non_camel_case_types)]
                    struct FetchOffsetSvc<T: Broker>(pub Arc<T>);
                    impl<
                        T: Broker,
                    > tonic::server::UnaryService<super::OffsetFetchRequest>
                    for FetchOffsetSvc<T> {
                        type Response = super::OffsetFetchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OffsetFetchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::fetch_offset(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FetchOffsetSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/CreateTopic" => {
                    #[allow(non_camel_case_types)]
                    struct CreateTopicSvc<T: Broker>(pub Arc<T>);
                    impl<
                        T: Broker,
                    > tonic::server::UnaryService<super::CreateTopicRequest>
                    for CreateTopicSvc<T> {
                        type Response = super::CreateTopicResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateTopicRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::create_topic(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateTopicSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/AddNode" => {
                    #[allow(non_camel_case_types)]
                    struct AddNodeSvc<T: Broker>(pub Arc<T>);
                    impl<T: Broker> tonic::server::UnaryService<super::AddNodeRequest>
                    for AddNodeSvc<T> {
                        type Response = super::AddNodeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddNodeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::add_node(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddNodeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/broker.Broker/RemoveNode" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveNodeSvc<T: Broker>(pub Arc<T>);
                    impl<T: Broker> tonic::server::UnaryService<super::RemoveNodeRequest>
                    for RemoveNodeSvc<T> {
                        type Response = super::RemoveNodeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RemoveNodeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Broker>::remove_node(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveNodeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BrokerServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "broker.Broker";
    impl<T> tonic::server::NamedService for BrokerServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
